# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_indicators', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleTrends',
        ),
    ]
