# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('key_indicators', '0002_delete_googletrends'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTrends',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
